/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.osmdroid;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;

// This proxy can be created by calling Tiosmdroid.createView({})
@Kroll.proxy(creatableInModule=TiosmdroidModule.class)
public class ViewProxy extends TiViewProxy {
	// Standard Debugging variables
	private static final String LCAT = "TiOsmdroidModule/ViewProxy";
	private static final boolean DBG = TiConfig.LOGD;

	private MapView view;
	private KrollDict location;
	private int zoomLevel = -1;

	// Constructor
	public ViewProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity activity) {
		view = new MapView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;

	 	if (zoomLevel > 0) {
	 		view.changeZoomLevel(zoomLevel);
	 	}

		return view;
	}

	// Methods
	@Kroll.method
	public void zoom(int delta) {
		if (view != null) {
			view.changeZoomLevel(delta);
		} else {
			zoomLevel = delta;
		}
	}

	@Kroll.method
	public void setLocation(KrollDict location)	{
		if(view == null) {
			this.location = location;
		} else {
			view.doSetLocation(location);
		}
	}

	@Kroll.method
	public void setMapType(int mapType) {
		this.setProperty(TiC.PROPERTY_MAP_TYPE, mapType, true);
	}
}